#!/bin/sh
# This selects which queue
#$ -q UI,AL
# One node. 1-16 cores on smp
#$ -pe smp 16
# Make the folder first
#$ -o /Users/twrner/outputs
#$ -e /Users/twrner/errors
~/anaconda/bin/python ~/skin_detection/op_elm/parallel_ensemble_elm.py /Users/twrner/extracted_data/tst_img__3701_3800.hdf5 ~/project_results/partial_skin_data_1201_1300_tst_img__3701_3800.hdf5 /Users/twrner/extracted_data/skin_data_1201_1300.elm 8192