
#!/bin/sh

# This selects which queue
#$ -q AL
# One node. 1-16 cores on smp
#$ -pe smp 16
# Make the folder first
#$ -o /Users/twrner/outputs
#$ -e /Users/twrner/errors

cd ~/skin_detection/op_elm


~/anaconda/bin/python elm_validation.py ~/extracted_data/skin_data_101_200.elm ~/extracted_data/skin_data_validation.hdf5 10000
~/anaconda/bin/python elm_validation.py ~/extracted_data/skin_data_1001_1100.elm ~/extracted_data/skin_data_validation.hdf5 10000
~/anaconda/bin/python elm_validation.py ~/extracted_data/skin_data_1101_1200.elm ~/extracted_data/skin_data_validation.hdf5 10000
~/anaconda/bin/python elm_validation.py ~/extracted_data/skin_data_1201_1300.elm ~/extracted_data/skin_data_validation.hdf5 10000
